---
title: "Annotating Transcriptomes with Trans2Kegg"
author: "Charles Roesel"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{Annotating Transcriptomes with Trans2Kegg}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

## Vignette Info

```{r}
outFile <- 'annot.csv'
library(Trans2Kegg)
#transFile <- system.file("extdata", "aiptasia.fa", package="Trans2Kegg")
transIds <- c("KXJ29331.1")
annotateTranscripts(transIds, "aiptasia.fa", outFile)
annot <- read.csv(outFile, stringsAsFactors=FALSE)
head(annot)
```

```{r}
mergeAnnotations(outFile)
```

Query the KEGG API to obtain pathway information, and produce a table of pathway to ortholog
mappings (Table 4), and pathway ID to pathway detail mappings (Table 5).

```{r}
#getPathways(outFile)
```

```{r}
#mergePaths("deCovAndCountDesc.csv", "dfPathsKos.csv", "dfPaths.csv") 
```

