mergeBlastKEGG <- function(){
  load("dfKeggToKO.RData")
  load("dfKoPathway.RData")
  load("dfUniKegg.RData")
  blastFile <- "blastSP.tsv"
  blastHits <- read.table(blastFile, sep="\t", header=F, quote="")
  colnames(blastHits) <- c("gene", "sp", "ident", "evalue", "cov")
  spBlast <- separate(blastHits, sp, c("spPrefix", "sp", "symbol"), sep = "\\|")
  spBlast <- separate(spBlast, gene, c("gene", "Tran"), sep = "-", remove=F)
  spBlast2 <- subset(spBlast, evalue < 1e-10 & cov > 50 & ident > 50,
    select=-c(spPrefix, Tran))
  spBlast3 <- separate(spBlast2, symbol, c("symbol", "species"), sep = "_")
  dfUniKegg <- separate(dfUniKegg, "uni", c("prefix", "uni"), sep=":")
  dfUniKegg <- subset(dfUniKegg, select=-c(prefix))
  blastToKegg <- merge(spBlast3, dfUniKegg, by.x="sp", by.y="uni")
  blastToKO <- merge(blastToKegg, dfKeggToKO, all.x=T, by="kegg")
  write.csv(blastToKO, file="blastToKO.csv")
  koSummCount <- aggregate(sp~gene.x+ko, blastToKO,FUN=NROW)
  koSummIdent <- aggregate(ident~gene.x+ko, blastToKO,FUN=mean)
  koSummCov <- aggregate(cov~gene.x+ko, blastToKO,FUN=mean)
  koSumm <- merge(koSummCount, koSummIdent)
  koSumm <- merge(koSumm, koSummCov)
  head(koSumm)
  write.csv(koSumm, file="koSumm.csv")
  koToDesc <- unique(subset(blastToKO, select=c("ko", "name", "desc")))
  koSummDesc<- merge(koSumm, koToDesc)
  koSummDesc<- merge(koSummDesc, dfKoPathway)
  write.csv(koSummDesc, file="koSummDesc.csv")
}
